ZakusochnayaViewWeb/Controllers/AddSkladElementController.cs
using System.Web.Mvc;
using ZakusochnayaServiceDAL.BindingModel;
using ZakusochnayaServiceDAL.Interfaces;

namespace ZakusochnayaViewWeb.Controllers
{
    public class AddSkladElementController : Controller
    {
        private IElementService ingredientService = Globals.ElementService;
        private ISkladService storageService = Globals.SkladService;
        private IMainService mainService = Globals.MainService;

        public ActionResult Index()
        {
            var ingredients = new SelectList(ingredientService.GetList(), "Id", "ElementName");
            ViewBag.Elements = ingredients;

            var storages = new SelectList(storageService.GetList(), "Id", "SkladName");
            ViewBag.Sklads = storages;
            return View();
        }

        [HttpPost]
        public ActionResult AddElementPost()
        {
            mainService.PutComponentOnStock(new SkladElementBindingModel
            {
                ElementId = int.Parse(Request["ElementId"]),
                SkladId = int.Parse(Request["SkladId"]),
                Number = int.Parse(Request["Number"])
            });
            return RedirectToAction("Index", "Home");
        }
    }
}

ZakusochnayaViewWeb/Controllers/OutputsController.cs
using PizzeriaWebView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZakusochnayaServiceDAL.Interfaces;

namespace ZakusochnayaViewWeb.Controllers
{
    public class OutputsController : Controller
    {
        public IOutputService service = Globals.OutputService;
        // GET: Pizzas
        public ActionResult Index()
        {
            return View(service.GetList());
        }

        public ActionResult Delete(int id)
        {
            service.DelElement(id);
            return RedirectToAction("Index");
        }
    }
}

ZakusochnayaViewWeb/Controllers/SkladController.cs
using System.Web.Mvc;
using ZakusochnayaServiceDAL.BindingModel;
using ZakusochnayaServiceDAL.Interfaces;

namespace ZakusochnayaViewWeb.Controllers
{
    public class SkladController : Controller
    {
        private ISkladService service = Globals.SkladService;

        public ActionResult List()
        {
            return View(service.GetList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreatePost()
        {
            service.AddElement(new SkladBindingModel
            {
                SkladName = Request["SkladName"]
            });
            return RedirectToAction("List");
        }
        public ActionResult Details(int id)
        {
            return View(service.GetElement(id));
        }

        public ActionResult Edit(int id)
        {
            var viewModel = service.GetElement(id);
            var bindingModel = new SkladBindingModel
            {
                Id = id,
                SkladName = viewModel.SkladName
            };
            return View(bindingModel);
        }

        [HttpPost]
        public ActionResult EditPost()
        {
            service.UpdElement(new SkladBindingModel
            {
                Id = int.Parse(Request["Id"]),
                SkladName = Request["SkladName"]
            });
            return RedirectToAction("List");
        }

        public ActionResult Delete(int id)
        {
            service.DelElement(id);
            return RedirectToAction("List");
        }
    }
}

ZakusochnayaViewWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Покупатели", "Pokupatels", "Home")</li>
                    <li>@Html.ActionLink("Компоненты", "Elements", "Home")</li>
                    <li>@Html.ActionLink("Продукты", "Outputs", "Home")</li>
                    <li>@Html.ActionLink("Заказы", "Zakazs", "Home")</li>
					<li>@Html.ActionLink("Склады", "List", "Sklad")</li>
					<li>@Html.ActionLink("Пополнить склад", "Index", "AddSkladElement")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>