ZakusochnayaViewWeb/Controllers/ZakazController.cs
using PizzeriaWebView;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZakusochnayaServiceDAL;
using ZakusochnayaServiceDAL.BindingModel;
using ZakusochnayaServiceDAL.BindingModels;
using ZakusochnayaServiceDAL.Interfaces;
using ZakusochnayaServiceDAL.ViewModel;
using ZakusochnayaServiceDAL.ViewModels;

namespace ZakusochnayaViewWeb.Controllers
{
    public class ZakazController : Controller
    {
        private IOutputService outputService = Globals.OutputService;
        private IMainService mainService = Globals.MainService;
        private IPokupatelService pokupatelService = Globals.PokupatelService;


        // GET: PizzaOrder
        public ActionResult Index()
        {
            return View(mainService.GetList());
        }

        public ActionResult Create()
        {
            var outputs = new SelectList(outputService.GetList(), "Id", "OutputName");
            var pokupatels = new SelectList(pokupatelService.GetList(), "Id", "PokupatelFIO");
            ViewBag.Outputs = outputs;
            ViewBag.Pokupatels = pokupatels;
            return View();
        }

        [HttpPost]
        public ActionResult CreatePost()
        {
            var customerId = int.Parse(Request["PokupatelId"]);
            var outputId = int.Parse(Request["OutputId"]);
            var Count = int.Parse(Request["Number"]);
            var totalCost = CalcSum(outputId, Count);

            mainService.CreateOrder(new ZakazBindingModel
            {
                PokupatelId = customerId,
                OutputId = outputId,
                Number = Count,
                Summa = totalCost

            });
            return RedirectToAction("Index");
        }

        private Decimal CalcSum(int outputId, int Count)
        {
            OutputViewModel output = outputService.GetElement(outputId);
            return Count * output.Cost;
        }

        public ActionResult SetStatus(int id, string status)
        {
            try
            {
                switch (status)
                {
                    case "Processing":
                        mainService.TakeOrderInWork(new ZakazBindingModel { Id = id });
                        break;
                    case "Ready":
                        mainService.FinishOrder(new ZakazBindingModel { Id = id });
                        break;
                    case "Paid":
                        mainService.PayOrder(new ZakazBindingModel { Id = id });
                        break;
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }


            return RedirectToAction("Index");
        }
    }
}

ZakusochnayaViewWeb/Views/Zakaz/Create.cshtml
@model ZakusochnayaServiceDAL.BindingModels.ZakazBindingModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("CreatePost", "Zakaz", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ZakazBindingModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PokupatelId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PokupatelId", ViewBag.Pokupatels as SelectList)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OutputId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OutputId", ViewBag.Outputs as SelectList)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZakusochnayaViewWeb/Views/Zakaz/Index.cshtml
@model IEnumerable<ZakusochnayaServiceDAL.ViewModels.ZakazViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@Html.ValidationSummary(true)
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PokupatelFIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OutputName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Summa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PokupatelFIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OutputName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Summa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Отдать на выполнение", "SetStatus", new { id=item.Id, status = "Processing" }) |
            @Html.ActionLink("Заказ готов", "SetStatus", new { id = item.Id, status = "Ready" }) |
            @Html.ActionLink("Заказ оплачен", "SetStatus", new { id = item.Id, status = "Paid" })
        </td>
    </tr>
}

</table>